swagger: "2.0"
info:
  title: My Budget API documentation
  description: Contains all available API endpoints in this codebase
  version: "1.0.0"
  termsOfService: "http://swagger.io/terms/"
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /transactions:
    get:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: Get all Transactions
      description: Return all transactions from the database
      produces:
        - application/json
      responses:
        "200":
          description: List of transactions
          schema:
            type: array
            items:
              $ref: "#/definitions/Transaction"
        "400":
          description: Invalid request
        "500":
          description: Internal Server Error
    post:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: Create a new Transaction
      description: Creates and stores a new transaction
      parameters:
        - in: body
          name: transaction
          required: true
          schema:
            $ref: "#/definitions/Transaction"
      produces:
        - application/json
      responses:
        "201":
          description: Transaction created successfully
        "400":
          description: Invalid input
        "500":
          description: Internal Server Error
  /transactions/{id}:
    get:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: Get One transaction by ID
      description: Fetch a single transaction based on its unique ID
      parameters:
        - name: id
          in: path
          required: true
          type: string
          description: MongoDB ObjectID of the transaction
      produces:
        - application/json
      responses:
        "200":
          description: Transaction retrieved
          schema:
            $ref: "#/definitions/Transaction"
        "404":
          description: Transaction not found
        "500":
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: Update a transaction
      description: Update the fields of a transaction by its ID
      parameters:
        - name: id
          in: path
          required: true
          type: string
        - in: body
          name: transaction
          required: true
          schema:
            $ref: "#/definitions/Transaction"
      produces:
        - application/json
      responses:
        "200":
          description: Transaction updated Successfully
        "400":
          description: Invalid input
        "500":
          description: Internal Server Error
    delete:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: Delete a transaction
      description: Remove a transaction from the database
      parameters:
        - name: id
          in: path
          required: true
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: Transaction deleted
        "404":
          description: Transaction not found
        "500":
          description: Internal Server Error
  /auth/signup:
    post:
      tags:
        - Auth Module
      summary: User registration
      description: Creates a new user account with a hashed password
      parameters:
        - in: body
          name: user
          required: true
          schema:
            $ref: "#/definitions/UserSignup"
      produces:
        - application/json
      responses:
        "201":
          description: User created successfully
        "400":
          description: Email already in use or invalid format
        "500":
          description: Internal server error

  /auth/login:
    post:
      tags:
        - Auth Module
      summary: User login
      description: Authenticates a user and returns a JWT token
      parameters:
        - in: body
          name: credentials
          required: true
          schema:
            $ref: "#/definitions/UserLogin"
      produces:
        - application/json
      responses:
        "200":
          description: Login successful
        "401":
          description: Incorrect credentials
        "500":
          description: Internal server error

  /auth/logout:
    post:
      tags:
        - Auth Module
      summary: Logout user
      description: Logs out the currently authenticated user by clearing the client-side token
      security:
        - Bearer: []
      responses:
        "200":
          description: Logout successful
        "401":
          description: Unauthorized or token missing

  /auth/profile:
    get:
      security:
        - Bearer: []
      tags:
        - Auth Module
      summary: Get user profile
      description: Returns the profile information of the currently authenticated user
      produces:
        - application/json
      responses:
        "200":
          description: User profile data
          schema:
            $ref: "#/definitions/UserProfile"
        "401":
          description: JWT token missing or invalid
        "500":
          description: Internal server error

    put:
      security:
        - Bearer: []
      tags:
        - Auth Module
      summary: Update user profile
      description: Updates the `userName`, `firstName`, and `lastName` of the authenticated user
      parameters:
        - in: body
          name: user
          required: true
          schema:
            $ref: "#/definitions/UserProfile"
      produces:
        - application/json
      responses:
        "200":
          description: Profile updated successfully
          schema:
            $ref: "#/definitions/UserProfile"
        "400":
          description: Invalid input data
        "401":
          description: JWT token missing or invalid
        "500":
          description: Internal server error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  Transaction:
    type: object
    required:
      - title
      - amount
      - type
    properties:
      title:
        type: string
        example: "Loyer Juin 2025"
        description: Title of the transaction
      amount:
        type: number
        example: -1450
        description: Amount of the transaction, can be negative or positive
      type:
        type: string
        enum: [income, expense]
        example: "expense"
        description: Type of transaction
      date:
        type: string
        format: date-time
        example: "2025-06-30T14:07:00.000Z"
        description: ISO 8601 date format
      category:
        type: string
        example: "loyer"
        description: Category label of the transaction
      note:
        type: string
        example: "Dernier loyer de la saison"
        description: Optional comment
      userId:
        type: string
        description: Owner user ID
  UserSignup:
    type: object
    required:
      - email,
      - password,
      - userName
    properties:
      email:
        type: string
      password:
        type: string
      userName:
        type: string
      firstName:
        type: string
      lastName:
        type: string

  UserLogin:
    type: object
    required:
      - email,
      - password
    properties:
      email:
        type: string
      password:
        type: string

  UserProfile:
    type: object
    properties:
      email:
        type: string
      userName:
        type: string
      firstName:
        type: string
      lastName:
        type: string
